version: 2
jobs:
  node:
    working_directory: ~/reactor
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Bundle Android JS Files
          command: node --expose-gc --max_old_space_size=5000 ./node_modules/react-native/local-cli/cli.js bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

      - save_cache:
          key: cache-bundle-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - android/app/src/main/assets/index.android.bundle
            - android/app/src/main/res/
            - node_modules/
  android:
    working_directory: ~/reactor
    docker:
      - image: circleci/android:api-28-alpha # gcloud is baked into this image
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-bundle-{{ .Environment.CIRCLE_WORKFLOW_ID }}
            - gradle-{{ checksum "~/reactor/android/build.gradle" }}

      - run:
          name: Build debug APK
          command: cd android && ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/reactor/android/.gradle
          key: gradle-{{ checksum "~/reactor/android/build.gradle" }}

      - store_artifacts:
          path: ~/reactor/android/app/build/outputs/apk/app-debug.apk
          destination: debug.apk

workflows:
  version: 2
  build-artifact:
    jobs:
      - node
      - android:
          requires:
            - node
